// client/src/Block.tsx
import React, { FC, useState } from "react";
import Color from "color";
import { url } from "inspector";
import styled from "styled-components";

const OPEN = -1;
const white = "#eee";
const black = "#111";

interface BlockProps {
  enabledState?: number;
  disabledState?: number;
  row?: number | null;
  col?: number | null;
  layerIndex?: number;
  onMouseDown?: Function;
  onMouseMove?: Function;
  onMouseUp?: Function;
  onClick?: Function;
  onRightClick?: Function;
  buttonDown?: any;
  size: number;
  color: string;
  transitionTime?: number;
}

const Block: FC<BlockProps> = ({
  enabledState = OPEN,
  disabledState = OPEN,
  row,
  col,
  layerIndex,
  onMouseDown,
  onMouseMove,
  onClick,
  onMouseUp,
  onRightClick,
  buttonDown,
  size,
  color,
  transitionTime = 0.2,
  children
}) => {
  const bg = enabledState === OPEN && disabledState === OPEN ? white : color;
  const disabled = disabledState === layerIndex;
  const backgroundImage = `url(${
    disabled
      ? `repeating-linear-gradient(
          45deg,transparent,transparent 3px,${bg} 3px,${bg} 6px
        )`
      : "none"
  })`;
  const textColor = Color(bg).isLight() ? black : white;

  const StyledBlock = styled.div`
    align-items: center;
    border: 1px solid rgba(0, 0, 0, 0.4);
    box-sizing: border-box;
    cursor: ${disabled ? "default" : "pointer"};
    display: flex;
    justify-content: center;
    position: relative;
    background-color: ${disabled ? white : bg};
    background-image: ${backgroundImage};
    color: ${textColor};
    font-size: ${size / 3}px;
    height: ${size}px;
    transition: all ${transitionTime}s ease-in-out;
    width: ${size}px;
  `;

  return (
    <StyledBlock
      onClick={e => {
        e.preventDefault();
        onClick && onClick(row, col);
      }}
      onContextMenu={e => {
        e.preventDefault();
        onRightClick && onRightClick(row, col);
      }}
      onMouseDown={e => {
        e.preventDefault();
        onMouseDown && onMouseDown(e, row, col);
      }}
      onMouseMove={e => {
        e.preventDefault();

        onMouseMove && onMouseMove(row, col);
      }}
      onMouseUp={e => {
        e.preventDefault();

        onMouseUp && onMouseUp(row, col);
      }}
    >
      {children}
    </StyledBlock>
  );
};

export default Block;

// client/src/Block.svelte
<script>
  import tinycolor from 'tinycolor2';

  export let row;
  export let col;
  export let state = -1;
  export let color;
  export let onClick;
  export let onMouseEnter;
  export let onMouseOver;
  export let onMouseLeave;
  export let onMouseDown;
  export let onMouseUp;
  export let onRightClick;
  export let transitionTime = 0.2;
  export let styles;
  export let buttonDown;

  const debug = false;
  const white = '#eee';
  const black = '#111';
  const red = '#d22';
  let hover = false;

  $: disabled = state === -2;
  $: bg = state > -1 ? color : white;
  $: textColor = tinycolor(bg).isLight() ? black : white;
  $: _styles = `
    background-color: ${bg};
    color: ${textColor};
    transition: all ${transitionTime}s ease-in-out;
    ${!!styles ? styles : ''}
  `;
</script>

<style>
  div {
    align-items: center;
    border: 1px solid rgba(0, 0, 0, 0.4);
    box-sizing: border-box;
    cursor: pointer;
    display: flex;
    font-size: 14px;
    height: 48px;
    justify-content: center;
    position: relative;
    width: 48px;
  }

  div.disabled {
    background-color: #eee;
    background-image: repeating-linear-gradient(
      45deg,
      transparent,
      transparent 3px,
      rgba(0, 0, 0, 0.15) 3px,
      rgba(0, 0, 0, 0.25) 6px
    );
  }
</style>

<div
  class:disabled
  style="{_styles}"
  on:click={() => {
    if (onClick) {
      onClick(row, col);
    }
  }}
  on:mousedown={(e) => {
    if (onMouseDown) {
      onMouseDown(e, row, col);
    }
  }}
  on:mouseup={() => {
    if (onMouseUp) {
      onMouseUp(row, col);
    }
  }}
  on:mouseenter={() => {
    hover = true;
    if (onMouseEnter) {
      onMouseEnter(row, col);
    }
  }}
  on:mouseover={() => {
    if (onMouseEnter) {
      onMouseEnter(row, col);
    }
  }}
  on:mouseleave={() => {
    hover = false;
    if (onMouseLeave) {
      onMouseLeave(row, col);
    }
  }}
  on:contextmenu={(e) => {
    if (onRightClick) {
      e.preventDefault();
      onRightClick(row, col);
    }
  }}
>
  {#if debug}
    <div style="position: absolute; top: 0; left: 0; font-size: 8px; height: 12px; width: 12px; display: flex: justifiy-content: center; align-content: center;">
      {state}
    </div>
  {/if}
  <slot />
</div>
